### ISSUE TITLE
dolt 0.12.0 schema import crash

### ISSUE THREAD

**Issue by danbst** [liquidata-inc/dolt#251]
```
$ dolt schema import --pks NDC -c formularies snippet.csv 
panic: runtime error: slice bounds out of range [42:41]

goroutine 37 [running]:
github.com/liquidata-inc/dolt/go/libraries/doltcore/table/untyped/csv.appendToken(0xc0000c8640, 0x7, 0x8, 0xc0005827c0, 0x30, 0x29, 0x29, 0x1, 0xc0000c8640, 0x7, ...)
        /Users/oscarbatori/Documents/dolt/go/libraries/doltcore/table/untyped/csv/line.go:100 +0x612
github.com/liquidata-inc/dolt/go/libraries/doltcore/table/untyped/csv.csvSplitLine(0xc0005827c0, 0x30, 0x1541733, 0x1, 0x180cd01, 0xc00036abc0, 0x0, 0x0, 0x0, 0x0)
        /Users/oscarbatori/Documents/dolt/go/libraries/doltcore/table/untyped/csv/line.go:54 +0x3c6
github.com/liquidata-inc/dolt/go/libraries/doltcore/table/untyped/csv.(*CSVReader).parseRow(0xc0000c8500, 0xc0005827c0, 0x30, 0x30, 0x0, 0x0, 0x0)
        /Users/oscarbatori/Documents/dolt/go/libraries/doltcore/table/untyped/csv/reader.go:157 +0x75
github.com/liquidata-inc/dolt/go/libraries/doltcore/table/untyped/csv.(*CSVReader).ReadRow(0xc0000c8500, 0x17fbe00, 0xc000348240, 0xc0005a0420, 0x0, 0xd51e00, 0x0)
        /Users/oscarbatori/Documents/dolt/go/libraries/doltcore/table/untyped/csv/reader.go:125 +0x1ef
github.com/liquidata-inc/dolt/go/libraries/doltcore/table/pipeline.ProcFuncForReader.func1(0x0, 0xc0005a0420, 0x0, 0x0, 0x0)
        /Users/oscarbatori/Documents/dolt/go/libraries/doltcore/table/pipeline/procfunc_help.go:76 +0x41
github.com/liquidata-inc/dolt/go/libraries/doltcore/table/pipeline.ProcFuncForSourceFunc.func1(0xc0005ac3f0, 0xc0003aa600, 0xc0003aa5a0, 0xc0005a0420)
        /Users/oscarbatori/Documents/dolt/go/libraries/doltcore/table/pipeline/procfunc_help.go:44 +0xa4
github.com/liquidata-inc/dolt/go/libraries/doltcore/table/pipeline.(*Pipeline).Start.func3(0xc0005ac3f0, 0xc0003aa600)
        /Users/oscarbatori/Documents/dolt/go/libraries/doltcore/table/pipeline/pipeline.go:239 +0x82
created by github.com/liquidata-inc/dolt/go/libraries/doltcore/table/pipeline.(*Pipeline).Start
        /Users/oscarbatori/Documents/dolt/go/libraries/doltcore/table/pipeline/pipeline.go:237 +0x3fc
```
Here's data snippet:
```
$ cat snippet.csv 
FORMULARY_ID,FORMULARY_VERSION,CONTRACT_YEAR,RXCUI,NDC,TIER_LEVEL_VALUE,QUANTITY_LIMIT_YN,QUANTITY_LIMIT_AMOUNT,QUANTITY_LIMIT_DAYS,PRIOR_AUTHORIZATION_YN,STEP_THERAPY_YN
00018000,15,2018,1551300,00002143380,2,Y,2,28,N,N
00018000,15,2018,1551306,00002143480,2,Y,2,28,N,N
00018000,15,2018,1745108,00002144511,2,N, , ,Y,N
00018000,15,2018,1946836,00002448354,2,Y,56,28,Y,N
00018000,15,2018,1946840,00002481554,2,Y,56,28,Y,N
00018000,15,2018,1946844,00002533754,2,Y,56,28,Y,N
00018000,15,2018,1946848,00002621654,2,Y,56,28,Y,N
00018000,15,2018,1872479,00002719001,2,N, , ,Y,N
00018000,15,2018,207834,00002733511,2,N, , ,Y,N
```

**Comment by timsehn** [comment]
We're looking at these right now.

**Comment by timsehn** [comment]
I was able to repro. I'm going to start by writing some bats tests for schema import. It's a newer feature and it's not adequately tested.

**Comment by timsehn** [comment]
```timothys-mbp:dolt-test timsehn$ cat empty-strings-null-values.csv 
pk,headerOne,headerTwo
a,"""""",1
b,"",2
c,,3
d,row four,""
e,row five,
f,row six,6timothys-mbp:dolt-tesdolt schema import --replace --pks=pk test empty-strings-null-values.csv 
CREATE TABLE `test` (
  `pk` TEXT NOT NULL COMMENT 'tag:0',
  `headerOne` TEXT COMMENT 'tag:6',
  `headerTwo` BIGINT COMMENT 'tag:7',
  PRIMARY KEY (`pk`)
);
```

Then modified the CSV and ran it again. 

```timothys-mbp:dolt-test timsehn$ cat empty-strings-null-values.csv 
pk,headerOne,headerTwo
a,"""""",1
b,"",2
c,,3
d,row four,""
e,row five,
f,row six,6
g, ,
timothys-mbp:dolt-test timsehn$ dolt schema import --replace --pks=pk test empty-strings-null-values.csv 
panic: runtime error: slice bounds out of range

goroutine 91 [running]:
github.com/liquidata-inc/dolt/go/libraries/doltcore/table/untyped/csv.appendToken(0xc000612088, 0x1, 0x1, 0xc000368cb6, 0x4, 0x2, 0x2, 0x2444d01, 0xc000612088, 0x1, ...)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/table/untyped/csv/line.go:100 +0x631
github.com/liquidata-inc/dolt/go/libraries/doltcore/table/untyped/csv.csvSplitLine(0xc000368cb6, 0x4, 0x21589d3, 0x1, 0x243a401, 0xc000130d20, 0x0, 0x0, 0x0, 0x0)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/table/untyped/csv/line.go:54 +0x3c9
github.com/liquidata-inc/dolt/go/libraries/doltcore/table/untyped/csv.(*CSVReader).parseRow(0xc0000b3000, 0xc000368cb6, 0x4, 0xc000368cb6, 0x4, 0x0, 0x0)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/table/untyped/csv/reader.go:157 +0x75
github.com/liquidata-inc/dolt/go/libraries/doltcore/table/untyped/csv.(*CSVReader).ReadRow(0xc0000b3000, 0x2429aa0, 0xc0002f4210, 0xc0000ce180, 0x0, 0x1969d00, 0x0)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/table/untyped/csv/reader.go:125 +0x1f8
github.com/liquidata-inc/dolt/go/libraries/doltcore/table/pipeline.ProcFuncForReader.func1(0x0, 0xc0000ce180, 0x0, 0x0, 0x0)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/table/pipeline/procfunc_help.go:76 +0x41
github.com/liquidata-inc/dolt/go/libraries/doltcore/table/pipeline.ProcFuncForSourceFunc.func1(0xc0002e4090, 0xc000290720, 0xc0002906c0, 0xc0000ce180)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/table/pipeline/procfunc_help.go:44 +0x94
github.com/liquidata-inc/dolt/go/libraries/doltcore/table/pipeline.(*Pipeline).Start.func3(0xc0002e4090, 0xc000290720)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/table/pipeline/pipeline.go:239 +0x78
created by github.com/liquidata-inc/dolt/go/libraries/doltcore/table/pipeline.(*Pipeline).Start
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/table/pipeline/pipeline.go:237 +0x3f5
```

Schema import can't handle a space in a column value. Just remove the space in column value (ie. ```foo,,bar``` not ```foo, ,bar```  and it will work as a workaround.

Incoming skipped bats test then fix.

**Comment by timsehn** [comment]
PR (https://github.com/liquidata-inc/dolt/pull/258) for a bats test to catch this out.

**Comment by timsehn** [comment]
This is fixed in the tip of master and will go out in the next release. We also have unit and bats tests for the case now so it won't regress. Thanks for using dolt and the bug report!
