### ISSUE TITLE
`dolt diff --summary` panic

### ISSUE THREAD

**Issue by timsehn** [liquidata-inc/dolt#630]
```
Timothys-MacBook-Pro:us-supreme-court-cases timsehn$ dolt diff --summary cases
diff --dolt a/cases b/cases
--- a/cases @ fadg8pam2i2s6d7hjgen4f27afpti7jr
+++ b/cases @ qfo8554mkh95dh9cvkrllriai88qv3r0
prev size: 7425, new size: 7425, adds: 0, deletes: 0, modifications: 0panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x15c9294]

goroutine 1836 [running]:
github.com/liquidata-inc/dolt/go/store/types.Null.Equals(...)
	/Users/timsehn/liquidata/git/dolt/go/store/types/null_value.go:46
github.com/liquidata-inc/dolt/go/store/types.Tuple.CountDifferencesBetweenTupleFields(0x26e7c60, 0xc00004a080, 0x33f3560, 0xc0003b46f1, 0x179, 0x1b59, 0x0, 0x0, 0x0, 0x26e7c60, ...)
	/Users/timsehn/liquidata/git/dolt/go/store/types/tuple.go:463 +0x1e5
github.com/liquidata-inc/dolt/go/libraries/doltcore/diff.reportChanges(0xc0006e4960, 0xc000012600, 0x0, 0x0)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/diff/diff_summary.go:67 +0x27b
github.com/liquidata-inc/dolt/go/libraries/doltcore/diff.Summary(0x26e7820, 0xc00023c240, 0xc000012600, 0x270fda0, 0xc00067c2d0, 0x270fda0, 0xc00016d720, 0x0, 0x0)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/diff/diff_summary.go:47 +0x29b
github.com/liquidata-inc/dolt/go/cmd/dolt/commands.diffSummary.func1(0xc000012600, 0x26e7820, 0xc00023c240, 0x270fda0, 0xc00067c2d0, 0x270fda0, 0xc00016d720, 0xc00041d800)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/diff.go:904 +0x9b
created by github.com/liquidata-inc/dolt/go/cmd/dolt/commands.diffSummary
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/diff.go:902 +0x144
Timothys-MacBook-Pro:us-supreme-court-cases timsehn$ dolt diff --summary transcripts
Timothys-MacBook-Pro:us-supreme-court-cases timsehn$ dolt diff --summary justices
Timothys-MacBook-Pro:us-supreme-court-cases timsehn$ dolt diff --schema 
diff --dolt a/cases b/cases
--- a/cases @ fadg8pam2i2s6d7hjgen4f27afpti7jr
+++ b/cases @ qfo8554mkh95dh9cvkrllriai88qv3r0
  CREATE TABLE cases (
    `term` LONGTEXT COMMENT 'tag:226'
    `case_name` LONGTEXT NOT NULL COMMENT 'tag:2284'
    `link` LONGTEXT COMMENT 'tag:5401'
    `decided_by` LONGTEXT COMMENT 'tag:14162'
-   `argued_on` LONGTEXT COMMENT 'tag:724'
    `petitioner` LONGTEXT COMMENT 'tag:4107'
    `respondent` LONGTEXT COMMENT 'tag:4611'
    `docket` LONGTEXT COMMENT 'tag:3338'
    `citation` LONGTEXT COMMENT 'tag:16221'
    `justia_link` LONGTEXT COMMENT 'tag:6656'
    `lower_court` LONGTEXT COMMENT 'tag:13189'
-   `granted_on` LONGTEXT COMMENT 'tag:12220'
-   `decided_on` LONGTEXT COMMENT 'tag:3091'
    `wiki_title` LONGTEXT COMMENT 'tag:11223'
    `wiki_litigants` LONGTEXT COMMENT 'tag:3200'
    `wiki_argue_date` LONGTEXT COMMENT 'tag:2173'
    `wiki_argue_year` LONGTEXT COMMENT 'tag:9026'
    `wiki_decide_date` LONGTEXT COMMENT 'tag:10223'
    `wiki_decide_year` LONGTEXT COMMENT 'tag:4405'
    `wiki_full_name` LONGTEXT COMMENT 'tag:6534'
    `wiki_us_vol` LONGTEXT COMMENT 'tag:14643'
    `wiki_us_page` LONGTEXT COMMENT 'tag:12852'
    `wiki_parallel_citations` LONGTEXT COMMENT 'tag:6714'
    `wiki_docket` LONGTEXT COMMENT 'tag:4870'
    `wiki_oral_argument` LONGTEXT COMMENT 'tag:682'
    `wiki_oral_reargument` LONGTEXT COMMENT 'tag:13048'
    `wiki_opinion_announcement` LONGTEXT COMMENT 'tag:4135'
    `wiki_prior` LONGTEXT COMMENT 'tag:15608'
    `wiki_subsequent` LONGTEXT COMMENT 'tag:4672'
    `wiki_holding` LONGTEXT COMMENT 'tag:11128'
    `wiki_scotus` LONGTEXT COMMENT 'tag:7064'
    `wiki_majority` LONGTEXT COMMENT 'tag:14039'
    `wiki_join_majority` LONGTEXT COMMENT 'tag:9440'
    `wiki_plurality` LONGTEXT COMMENT 'tag:14516'
    `wiki_join_plurality` LONGTEXT COMMENT 'tag:12578'
    `wiki_concurrence` LONGTEXT COMMENT 'tag:15547'
    `wiki_join_concurrence` LONGTEXT COMMENT 'tag:5710'
    `wiki_concurrence2` LONGTEXT COMMENT 'tag:1796'
    `wiki_join_concurrence2` LONGTEXT COMMENT 'tag:7857'
    `wiki_concurrence3` LONGTEXT COMMENT 'tag:8408'
    `wiki_concurrence_dissent` LONGTEXT COMMENT 'tag:6737'
    `wiki_join_concurrence_dissent` LONGTEXT COMMENT 'tag:7700'
    `wiki_dissent` LONGTEXT COMMENT 'tag:7277'
    `wiki_join_dissent` LONGTEXT COMMENT 'tag:5150'
    `wiki_dissent2` LONGTEXT COMMENT 'tag:11314'
    `wiki_join_dissent2` LONGTEXT COMMENT 'tag:1852'
    `wiki_not_participating` LONGTEXT COMMENT 'tag:1732'
    `wiki_laws_applied` LONGTEXT COMMENT 'tag:11960'
+   `decided_on` DATE COMMENT 'tag:7029'
+   `argued_on` DATE COMMENT 'tag:10328'
+   `granted_on` DATE COMMENT 'tag:1734'
     PRIMARY KEY (`case_name`)
  );
```

All I did was change columns from strings to dates.

**Comment by timsehn** [comment]
Repro:
```
Timothys-MacBook-Pro:tmp timsehn$ dolt clone Liquidata/us-supreme-court-cases
cloning https://doltremoteapi.dolthub.com/Liquidata/us-supreme-court-cases
1,039 of 1,039 chunks complete. 0 chunks being downloaded currently.
Timothys-MacBook-Pro:tmp timsehn$ cd us-supreme-court-cases/
Timothys-MacBook-Pro:us-supreme-court-cases timsehn$ dolt log 
commit rmkd53ocd7muv4urbito5q8e27k2tt24
Author: Tim Sehn <tim@liquidata.co>
Date:   Mon Apr 27 17:00:18 -0700 2020

	Fix schema of cases table

commit ipng05fljvavag5c4n99okqifb711ufu
Author: Tim Sehn <tim@liquidata.co>
Date:   Mon Apr 27 16:36:23 -0700 2020

	Fixed schema of transcripts table

commit tk5chbnh5q7v0iu5f3l0k3er1dlsgtof
Author: Tim Sehn <tim@liquidata.co>
Date:   Mon Apr 27 16:21:58 -0700 2020

	Import to get started. Will work on schema. cases and transcripts tables have incorrect types.

commit idk7bsomk477hctqhghnlv5phn2kr9ns
Author: Tim Sehn <tim@liquidata.co>
Date:   Sun Apr 26 14:00:11 -0700 2020

	Renamed ethnic column is_ethnic to reflect that it is boolean

commit nksnfatlurv2me37h0mibt8pm8qfdhl4
Author: Tim Sehn <tim@liquidata.co>
Date:   Sun Apr 26 13:01:46 -0700 2020

	Added README

commit 2vnra93463fg9ebfclthbjcaq1vv9ufh
Author: Tim Sehn <tim@liquidata.co>
Date:   Sun Apr 26 12:57:49 -0700 2020

	Added justices table with proper schema

commit 6fqh5vqmupn3lep5mu3fg7fmmupm1vg7
Author: Tim Sehn <tim@liquidata.co>
Date:   Thu Apr 23 14:03:33 -0700 2020

	Initialize data repository

Timothys-MacBook-Pro:us-supreme-court-cases timsehn$ dolt diff --summary rmkd53ocd7muv4urbito5q8e27k2tt24 ipng05fljvavag5c4n99okqifb711ufu
diff --dolt a/cases b/cases
--- a/cases @ fadg8pam2i2s6d7hjgen4f27afpti7jr
+++ b/cases @ qfo8554mkh95dh9cvkrllriai88qv3r0
7,424 Rows Unmodified (99.99%)                                        
0 Rows Added (0.00%)
0 Rows Deleted (0.00%)
1 Row Modified (0.01%)
6 Cells Modified (0.00%)
(7,425 Entries vs 7,425 Entries)

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x15c9294]

goroutine 422 [running]:
github.com/liquidata-inc/dolt/go/store/types.Null.Equals(...)
	/Users/timsehn/liquidata/git/dolt/go/store/types/null_value.go:46
github.com/liquidata-inc/dolt/go/store/types.Tuple.CountDifferencesBetweenTupleFields(0x26e7c60, 0xc0005be000, 0x33f3560, 0xc00036a6f1, 0x179, 0x1b59, 0x0, 0x0, 0x0, 0x26e7c60, ...)
	/Users/timsehn/liquidata/git/dolt/go/store/types/tuple.go:463 +0x1e5
github.com/liquidata-inc/dolt/go/libraries/doltcore/diff.reportChanges(0xc000654120, 0xc0003549c0, 0x0, 0x0)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/diff/diff_summary.go:67 +0x27b
github.com/liquidata-inc/dolt/go/libraries/doltcore/diff.Summary(0x26e7820, 0xc0006cc1e0, 0xc0003549c0, 0x270fda0, 0xc0003c27d0, 0x270fda0, 0xc0000e7ea0, 0x0, 0x0)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/diff/diff_summary.go:47 +0x29b
github.com/liquidata-inc/dolt/go/cmd/dolt/commands.diffSummary.func1(0xc0003549c0, 0x26e7820, 0xc0006cc1e0, 0x270fda0, 0xc0003c27d0, 0x270fda0, 0xc0000e7ea0, 0xc0005f7610)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/diff.go:904 +0x9b
created by github.com/liquidata-inc/dolt/go/cmd/dolt/commands.diffSummary
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/diff.go:902 +0x144
```

**Comment by timsehn** [comment]
`dolt diff rmkd53ocd7muv4urbito5q8e27k2tt24 ipng05fljvavag5c4n99okqifb711ufu` works fine...
