### ISSUE TITLE
Index out of range panic

### ISSUE THREAD

**Issue by timsehn** [liquidata-inc/dolt#680]
Repro:

1. Clone Liquidata/nba-players
2. run`dolt sql -q "update season_totals_regular_season join players on season_totals_regular_season.player_id=players.id set pts=pts+2 where players.full_name='James Harden' and season_id='2019-20'"`

Error:

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/liquidata-inc/dolt/go/libraries/doltcore/sqle.SqlRowToDoltRow(0x354ecd8, 0xc0022cb800, 0x20, 0x20, 0x27b51c0, 0xc000cc3350, 0x0, 0x0, 0xc00233b1f8, 0x1543a96)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/sqle/rows.go:108 +0x47b
github.com/liquidata-inc/dolt/go/libraries/doltcore/sqle.(*tableEditor).Update(0xc0006eec30, 0xc0002c0c40, 0xc0022cb800, 0x20, 0x20, 0xc0022cba00, 0x20, 0x20, 0x38, 0x0)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/sqle/table_editor.go:162 +0xa2
github.com/liquidata-inc/go-mysql-server/sql/plan.(*Update).Execute(0xc0005e4ea0, 0xc0002c0c40, 0x1da02bf, 0x27c32e0, 0xc0005e3840, 0x27d84c0)
	/Users/timsehn/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200508170854-b74c3414aebf/sql/plan/update.go:113 +0x347
github.com/liquidata-inc/go-mysql-server/sql/plan.(*Update).RowIter(0xc0005e4ea0, 0xc0002c0c40, 0xc000770280, 0xc000551520, 0xc00017b740, 0xc000260120)
	/Users/timsehn/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200508170854-b74c3414aebf/sql/plan/update.go:145 +0x4d
github.com/liquidata-inc/go-mysql-server/sql/plan.(*QueryProcess).RowIter(0xc0005e3840, 0xc0002c0c40, 0x27c3b80, 0xc00017b650, 0x27c32e0, 0xc0005e3840)
	/Users/timsehn/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200508170854-b74c3414aebf/sql/plan/process.go:35 +0x41
github.com/liquidata-inc/go-mysql-server.(*Engine).Query(0xc0006021e0, 0xc0002c0c40, 0x7ffeefbfee3c, 0xb2, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/Users/timsehn/go/pkg/mod/github.com/liquidata-inc/go-mysql-server@v0.5.1-0.20200508170854-b74c3414aebf/engine.go:154 +0x2e3
github.com/liquidata-inc/dolt/go/cmd/dolt/commands.(*sqlEngine).query(...)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/sql.go:1113
github.com/liquidata-inc/dolt/go/cmd/dolt/commands.processQuery(0xc0003c8070, 0x7ffeefbfee3c, 0xb2, 0xc0005735e0, 0xc0007701e0, 0x1, 0x1, 0xc0005735e0, 0x0, 0x0, ...)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/sql.go:788 +0xa88
github.com/liquidata-inc/dolt/go/cmd/dolt/commands.execQuery(0xc0003c8070, 0xc000848060, 0xc00031ba58, 0x7ffeefbfee3c, 0xb2, 0x27cfa00, 0x0, 0x0, 0x0)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/sql.go:355 +0x109
github.com/liquidata-inc/dolt/go/cmd/dolt/commands.SqlCmd.Exec(0x23e08fd, 0x6, 0x27b4fc0, 0xc000848150, 0xc000496a50, 0x8, 0xc0000e6020, 0x2, 0x2, 0xc00033f760, ...)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/sql.go:226 +0xbf1
github.com/liquidata-inc/dolt/go/cmd/dolt/cli.SubCommandHandler.Exec(0x23dee85, 0x4, 0x23f1f07, 0x11, 0xc00000c3c0, 0x1e, 0x1e, 0x0, 0x27b4fc0, 0xc000848150, ...)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/cli/command.go:160 +0x484
main.runMain(0x0)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:210 +0xc8f
main.main()
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:97 +0x22
```

**Comment by VinaiRachakonda** [comment]
Update on joins throw an error now. Closing
