### ISSUE TITLE
dolt push segmentation fault

### ISSUE THREAD

**Issue by timsehn** [liquidata-inc/dolt#95]
I downloaded the latest Tatoeba sentence translation database and imported it. When I tried to push it up to DoltHub, it threw a segmentation fault on the tip of master:

timothys-mbp:tatoeba-sentence-translations timsehn$ dolt push origin master
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x187a2d3]

goroutine 1 [running]:
github.com/liquidata-inc/dolt/go/store/datas.putChunks(0x22a9ca0, 0xc0003d2120, 0x22c3040, 0xc0010b0be0, 0xc00144e000, 0x1c9, 0x220, 0xc001250ff0, 0xc001250fc0, 0x2dbba00, ...)
	/Users/timsehn/liquidata/git/dolt/go/store/datas/pull.go:300 +0x153
github.com/liquidata-inc/dolt/go/store/datas.pull(0x22a9ca0, 0xc0003d2120, 0x22c3040, 0xc0003a40c0, 0x22c3040, 0xc0010b0be0, 0x0, 0x0, 0x2d7a498, 0xc00114d000, ...)
	/Users/timsehn/liquidata/git/dolt/go/store/datas/pull.go:211 +0x775
github.com/liquidata-inc/dolt/go/store/datas.Pull(...)
	/Users/timsehn/liquidata/git/dolt/go/store/datas/pull.go:157
github.com/liquidata-inc/dolt/go/libraries/doltcore/doltdb.(*DoltDB).PushChunks(0xc000394bb0, 0x22a9ca0, 0xc0003d2120, 0xc000394010, 0xc00040ec00, 0xc00014c3c0, 0xc001091401, 0x0)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/doltdb/doltdb.go:632 +0x20b
github.com/liquidata-inc/dolt/go/libraries/doltcore/env/actions.Push(0x22a9ca0, 0xc0003d2120, 0x7ffeefbffc39, 0x6, 0xc0004ea118, 0x6, 0x7ffeefbffc39, 0x6, 0xc000394010, 0xc000394bb0, ...)
	/Users/timsehn/liquidata/git/dolt/go/libraries/doltcore/env/actions/remotes.go:43 +0x134
github.com/liquidata-inc/dolt/go/cmd/dolt/commands.pushToRemoteBranch(0x22a9ca0, 0xc0003d2120, 0x22a3ce0, 0xc0000dc290, 0x22a3ce0, 0xc0000dc2c0, 0x22a3d60, 0xc00000e240, 0xc000394010, 0xc000394bb0, ...)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/push.go:248 +0x3e6
github.com/liquidata-inc/dolt/go/cmd/dolt/commands.Push(0x22a9ca0, 0xc0003d2120, 0xc0000eeaf0, 0x9, 0xc0000fc020, 0x2, 0x2, 0xc00016c000, 0x9)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/commands/push.go:180 +0xca1
github.com/liquidata-inc/dolt/go/cmd/dolt/cli.GenSubCommandHandler.func1(0x22a9ca0, 0xc0003d2120, 0x1ff8eff, 0x4, 0xc0000fc010, 0x3, 0x3, 0xc00016c000, 0xc0003d2090)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/cli/command.go:93 +0x204
main.runMain(0x0)
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:174 +0x983
main.main()
	/Users/timsehn/liquidata/git/dolt/go/cmd/dolt/dolt.go:82 +0x22

**Comment by timsehn** [comment]
Fixed in the latest master
